### ISSUE TITLE
Tracing with OpenTelemetry

### ISSUE THREAD

**Issue by tronghn** [nais/wonderwall#116]
We should instrument critical paths with OpenTelemetry for better tracing (e.g. for reverseproxy calls, external calls to Redis/session store, etc.)

**Comment by jksolbakken** [comment]
Traces rapporteres nå for HTTP-ting (Chi) og Redis. Tempo er etter det jeg kan se kun tilgjengelig som datasource på 

![Image](https://github.com/nais/wonderwall/assets/5025898/6191a780-ca7e-4bbc-89fb-29d525a6e8a4)

grafana.nav.cloud.nais.io, mens Wonderwall sitt nåværende dashboard er på monitoring.nais.io. Setter denne til "done", så får evt. flytting/samling av dashboards bli en egen greie.
