### ISSUE TITLE
AllowAllUsers + groups doenst emit groups claim

### ISSUE THREAD

**Issue by Reasonable-Solutions** [nais/wonderwall#191]
The interface gets weird here. 
If i have a solution that is allowAllUsers _and_ i want to segregate some users by group, it would be nice if I could 
say allowAllUsers and also emit group claims if the user is in any of these groups. 

The current implementation seems to only support adding the group claims by also rejecting users not in the specified group. 
The current workaround seems to be to request group claims for the group you want and the group that contains everyone (000-office-365-someting). 

Could we add a piece of configuration for emitting claims for groups without doing access control on said groups?

**Comment by tronghn** [comment]
This isn't really something that Wonderwall concerns itself with, but rather the configuration in Azure AD (which is reconciled by https://github.com/nais/azurerator/).

But to answer your question: the `allowAllUsers` toggle is in fact a shortcut that adds groups that contain all users. You can use this independently with or without additional groups that you want emitted in the `group` claim found in the user's token.

For example, given this configuration:

```yaml
...
claims:
  groups:
    - id: <some-group-uuid>
```

...results in issued tokens with the claim (given a user that is a direct member of `some-group`):

```json
{
  ...
  "groups": ["<some-group-uuid>"]
  ...
}
```

Adding `allowAllUsers: true` to the above example:

```yaml
...
allowAllUsers: true
claims:
  groups:
    - id: <some-group-uuid>
```

...results in issued tokens with the claim (given a user that is a direct member of `some-group`):

```json
{
  ...
  "groups": ["<all-users-group-uuid>", "<some-group-uuid>"]
  ...
}
```

...and for users that aren't members of `some-group`:

```json
{
  ...
  "groups": ["<all-users-group-uuid>"]
  ...
}
```
