### ISSUE TITLE
Less spammy logging on startup

### ISSUE THREAD

**Issue by karl-run** [nais/wonderwall#262]
A bit nit-picky, but could the configuration logging that wonderwall does on startup be done as a single multi-line log statement instead of 40+ single lines? :smile: 

![image](https://github.com/nais/wonderwall/assets/1507032/190f85ae-26d4-4c00-b622-2100f4dca39b)

**Comment by tronghn** [comment]
It probably could, but you could also just filter these out based on the `logger` field, e.g. `-x_logger:(wonderwall.config OR openid.config.client OR openid.config.provider)` - though we should probably just use the same logger for all of these configs 🙁

**Comment by karl-run** [comment]
Yeah I usually filter out wonderwall, linkerd-proxy, linkerd-init etc. when looking at app logs. Nothing big, just something I've noticed when sanity checking my deploys. :sweat_smile:

**Comment by tronghn** [comment]
Completely understandable. I'll see if we can clean these up a bit 😄
