### ISSUE TITLE
Compatibility with OpenID providers without support for front-channel logout

### ISSUE THREAD

**Issue by tronghn** [nais/wonderwall#7]
Wonderwall currently requires the `sid` claim in `id_tokens`, regardless of whether or not the OpenID Provider supports the [OpenID Connect Front-Channel Logout 1.0](https://openid.net/specs/openid-connect-frontchannel-1_0.html) specification. 

We should correctly disable this requirement if the OP does not explicitly declare support for this in its metadata discovery document (in the property `frontchannel_logout_session_supported`).

Equivalently, if only the `frontchannel_logout_supported` property is set, but not `frontchannel_logout_session_supported` - as in the case of Azure AD - the `sid` claim should also _not_ be required.

If the OP implements the [OpenID Connect Session Management 1.0](https://openid.net/specs/openid-connect-session-1_0.html) specification - i.e. the `check_session_iframe` property is set - we should rather look for the `session_state` parameter in the Authentication response from the OP.

If none of these are supported, the session ID should be randomly generated (but we must ensure that there are no collisions).

**Comment by ybelMekk** [comment]
I'll give it a try while in quarantine :D
